language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip freeze
  - pip install --upgrade .[test]
  - pip freeze
# command to run tests
script:
  - pytest
  - pytest --cov-report annotate
  - bash <(curl -s https://codecov.io/bash)
