language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - python -m venv venv
  - venv/bin/python -m pip freeze
  - venv/bin/python -m pip install --upgrade pip setuptools wheel
  - venv/bin/python -m pip freeze
  - venv/bin/python -m pip install --upgrade .[test]
  - venv/bin/python -m pip freeze
# command to run tests
script:
  - venv/bin/python -m pytest
  - venv/bin/python -m pytest --cov-report annotate
  - bash <(curl -s https://codecov.io/bash)
