[tool.pytest.ini_options]
minversion = "6.1.2"
addopts = "--strict-config --strict-markers --cov=. --cov-report=term-missing:skip-covered"
[build-system]
requires = [
  "setuptools >= 40.9.0",
  "wheel",
]
build-backend = "setuptools.build_meta"